### ISSUE TITLE
Update colour palette

### ISSUE THREAD

**Issue by trullock** [MyUNiDAYS/competency-framework#5]
Chase Chloe for approved palette at start of July

**Comment by jaketurton** [comment]
To add:

![Screen Shot 2019-07-17 at 16 11 53](https://user-images.githubusercontent.com/7407426/61468342-02843f80-a975-11e9-8326-50d5c22ad2a4.png)

**Comment by trullock** [comment]
Use a sprinkling of these to enrich the UI away from the current blue/gree only pallete
