### ISSUE TITLE
Going directly to a saved-review URL doesn't render the results properly

### ISSUE THREAD

**Issue by trullock** [MyUNiDAYS/competency-framework#61]
Review summary page only renders correctly when coming from the review input page

**Comment by AndyRigley** [comment]
Review Summary page gets stuck in a loop when **revisiting** a prebuilt link.
This 'may' have something to do with auto-accepting popups?
example link : https://progression.myunidays.com/roles/software-engineer/junior-software-engineer/review/summary?reviewId=hqO34BxuPASe33fVzAU3

**Comment by trullock** [comment]
@AndyRigley Can you retest this? Should be fixed
